---
- name: Backup webdav
  hosts: "{{ my_host | default('localhost') }}"
  become: false
  gather_facts: true

  vars_files:
    - variables.yml

  tasks:
    # Verify
    - name: Ensure necessary variables are defined
      tags: verify
      ansible.builtin.assert:
        that:
          - my_user | regex_search('^[a-z]+')
          - webdav_mount | regex_search('^/')
          - device_mountpoint | regex_search('^/')
          - backup_path | regex_search('^/')
        success_msg: "You have set all necessary variables to run this playbook"
        fail_msg: |
          You have NOT set all necessary variables to run this playbook.
          Please set the following variables:
          my_user, webdav_mount, device_mountpoint, backup_path

    - name: Verifying webdav mount, backup path, backup archive and device mountpoint
      tags: verify
      loop:
        - "{{ dir_paths }}"
      register: verify_paths
      ansible.builtin.stat:
        path: "{{ item }}"

    - name: Output verification of the last task
      failed_when: verify_paths.stat.isdir is false
      tags: verify
      ansible.builtin.debug:
        msg: "All paths are valid"

    - name: Ensure user automount systemd services are running
      tags: verify
      loop:
        - "{{ automount_services }}"
      ansible.builtin.systemd:
        name: {{ item }}
        scope: user
        state: started
        
    # Archive previous backup - BELOW ARE NOT MAKING SENSE...
    - name: Counting the number of backup archives
      tags: archive
      register: archive_count
      ansible.builtin.find:
        paths: "{{ archive_path }}"
        patterns: '*.xz'

    - name: Archiving last backup
      tags: archive
      when: archive_count > 0
      community.general.archive:
        path: "{{ backup_path }}"
        dest: "{{ archive_path }}/{{ backup_path | basename + timestamp }}"
        format: xz